routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\EntityController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ReserveController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TermController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::GET('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {

        Route::get('setting', [SettingController::class, 'index'])->name('setting');
        Route::post('setting', [SettingController::class, 'update'])->name('updatesetting');

        Route::resource('roles', RoleController::class)->except(['show']);

        Route::resource('terms', TermController::class)->except(['show']);
        
        Route::resource('admins', AdminsController::class)->except(['show']);
        Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

        Route::resource('users', UsersController::class)->except(['show']);
        Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');

        Route::resource('contactus', ContactController::class)->except(['create','edit']);
        Route::resource('aboutus', AboutController::class)->except(['show']);

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::get('categoryactive', [CategoryController::class, 'CategoryStatus'])->name('categoryactive');

        Route::resource('regions', RegionController::class)->except(['show']);
        Route::get('regionactive', [RegionController::class, 'RegionStatus'])->name('regionactive');

        Route::resource('entities', EntityController::class);
        Route::put('entityupdate2/{id}', [EntityController::class, 'updateStep2'])->name('updatestep2');
        Route::get('entityactive', [EntityController::class, 'EntityStatus'])->name('entityactive');
        Route::post('entityimagestore',[EntityController::class, 'EntityImage'])->name('entityimg');
        Route::get('entityimageshow',[EntityController::class, 'ShowImage'])->name('entityimgshow');
        Route::post('entityimagedelete',[EntityController::class, 'EntityImageDelete'])->name('entityimgdelete');

        Route::post('entityfeatadd',[EntityController::class, 'EntityFeatureAdd'])->name('entityfeatadd');
        Route::get('entityfeatall',[EntityController::class, 'EntityFeatureAll'])->name('entityfeatall');
        Route::delete('entityfeatdelete/{id}',[EntityController::class, 'EntityFeatureDelete'])->name('featureDelete');

        Route::post('entityfiltadd',[EntityController::class, 'EntityFilterAdd'])->name('entityfiltadd');
        Route::delete('entityfiltdelete/{id}',[EntityController::class, 'EntityFilterDelete'])->name('filterDelete');
        Route::delete('entityfiltoptiondelete/{id}',[EntityController::class, 'EntityOptionDelete'])->name('optionDelete');
        Route::post('entityoptiadd',[EntityController::class, 'EntityOptionAdd'])->name('entityoptionadd');

        Route::resource('reserves', ReserveController::class);
        Route::get('allres',[ReserveController::class, 'GetAllReseve'])->name('allreserve');
        
        });

        
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('/', function () {
            return view('welcome');
        });
        
        Auth::routes();
        
        Route::get('/home', [HomeController::class, 'index'])->name('home');
    });

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
   // public $guarded = [];

    protected $fillable = ['name'];

    public function scopeWhereRoleNot($query, $role_name)
    {
        return $query->whereNotIn('name', (array)$role_name);
    }

    public function scopeIdDescending($query)
   {
        return $query->orderBy('id','DESC');
   }   


}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Validation\Rule;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:roles-read')->only(['index']);
        $this->middleware('permission:roles-create')->only(['create','store']);
        $this->middleware('permission:roles-update')->only(['edit','update']);
        $this->middleware('permission:roles-delete')->only(['destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        

        if ($request->ajax()) {
        $data = Role::idDescending()->whereRoleNot(['super_admin'])->with('permissions')->get();

        return Datatables::of($data)
        ->addIndexColumn()
        ->addColumn('action', function($row){

        if (Auth::guard('admin')->user()->hasPermission('roles-update')){
         $btn ='<a href="' .route("roles.edit", $row->id). '" type="button" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></i></a> &nbsp;';
        }else{
            $btn = '<a  href="" class="btn btn-primary btn-xs disabled">Edit</i></a>';
        }

        if (Auth::guard('admin')->user()->hasPermission('roles-delete')){
            $btn = $btn.
            '<form class=" delete"  action="' . route("roles.destroy", $row->id) . '"  method="POST" id="delform"
            style="display: inline-block; right: 50px;" >
            <input name="_method" type="hidden" value="DELETE">
            <input type="hidden" name="_token" value="' . csrf_token() . '">
            <button type="submit" class="btn btn-danger btn-xs" title=" ' . 'Delete' . ' "><i class="fa fa-trash-o"></i></button>
                </form>';
        }else{
            $btn = $btn. '<button class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></button>';
        }

                    return $btn;
                })

                ->rawColumns(['action'])
                ->make(true);

        }

        return view('admin.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $models = ['admins', 'roles','users','aboutus','terms','entities','categories','reserves','contactus','settings'];
        $maps = ['create', 'read', 'update', 'delete'];
        return view('admin.roles.create',compact('models','maps'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:roles',
            'permissions' => 'required|array|min:1',
        ]);
        $role = Role::create($request->all());
        $role->attachPermissions($request->permissions);
        session()->flash('success', __('admin.addsuccessfully'));
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $models = ['admins', 'roles','users','aboutus','terms','entities','categories','reserves','contactus','settings'];
        $maps = ['create', 'read', 'update', 'delete'];
        $role = Role::findOrFail($id);
        return view('admin.roles.edit',compact('role','models','maps'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $request->validate([
            'name' => ['required',Rule::unique('roles')->ignore($id)],
            'permissions' => 'required|array|min:1',
        ]);

        $role->update($request->all());
        $role->syncPermissions($request->permissions);
        session()->flash('success', __('admin.updatesuccessfully'));
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();
        return response()->json(['status'=>'success']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layout.master')

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.roles')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.roles')</a></li>
                            <li class="active">@lang('admin.addroles')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <form action="{{route('roles.store')}}" method="post" data-parsley-validate>
                                @csrf
                                @method('post')
                          
                                <div class="form-group col-md-6">
                                    <label for="name">@lang('admin.namerole')</label>
                                    <input type="text" name="name"
                                     value="{{old('name')}}" 
                                     required parsley-trigger="change" 
                                     placeholder="@lang('admin.namerole')" 
                                     class="form-control" >
                                </div>
                                <div class="form-group">
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>@lang('admin.model')</th>
                                            <th>@lang('admin.permissions')</th>
                                        </tr>
                                        @foreach($models as $index=>$model)
                                        @if($model == 'settings')
                                        <?php $maps = ['read', 'update']; ?>
                                        @endif
                                        @if($model == 'contactus')
                                        <?php $maps = ['read', 'delete']; ?>
                                        @endif
                                            <tr>
                                                <td style="width:5%">{{$index+1}}</td>
                                                <td style="width:5%">@lang('admin.'.$model)</td>
                                                <td>
                                                    <select class="form-control select2me" name="permissions[]" multiple>
                                                        @foreach($maps as $index=>$map)
                                                            <option value="{{$model.'-'.$map}}">@lang('admin.'.$map)</option>
                                                        @endforeach
                                                    </select>
                                                </td>
                                            </tr>
                                        @endforeach

                                        </tbody>
                                    </table>
                                </div>
                                
                                <div class="clearfix"></div>
                                <div class="form-group text-right m-b-0">
                                    @if(Auth::guard('admin')->user()->hasPermission('roles-create'))
                                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.add')</button>
                                    @else
                                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.add')</button>
                                    @endif
                                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.roles')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.roles')</a></li>
                            <li class="active">@lang('admin.editroles')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <form action="{{route('roles.update',$role->id)}}" method="post" data-parsley-validate>
                                @csrf
                                @method('put')
                          
                                <div class="form-group col-md-6">
                                    <label for="name">@lang('admin.namerole')</label>
                                    <input type="text" name="name"
                                     value="{{$role->name}}" 
                                     required parsley-trigger="change" 
                                     placeholder="@lang('admin.namerole')" 
                                     class="form-control" >
                                </div>
                                <div class="form-group">
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>@lang('admin.model')</th>
                                            <th>@lang('admin.permissions')</th>
                                        </tr>
                                        @foreach($models as $index=>$model)
                                        @if($model == 'settings')
                                        <?php $maps = ['read', 'update']; ?>
                                        @endif
                                            <tr>
                                                <td style="width:5%">{{$index+1}}</td>
                                                <td style="width:5%">@lang('admin.'.$model)</td>
                                                <td>
                                                    <select class="form-control select2me" name="permissions[]" multiple>
                                                        @foreach($maps as $index=>$map)

                                                        <option value="{{$model.'-'.$map}}" {{$role->hasPermission($model.'-'.$map) ? 'selected':''}}>@lang('admin.'.$map)</option>
                                                        @endforeach
                                                    </select>
                                                </td>
                                            </tr>
                                        @endforeach

                                        </tbody>
                                    </table>
                                </div>
                                
                                <div class="clearfix"></div>
                                <div class="form-group text-right m-b-0">
                                    @if(Auth::guard('admin')->user()->hasPermission('roles-update'))
                                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.edit')</button>
                                    @else
                                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.edit')</button>
                                    @endif
                                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layout.master')

@section('content')


<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.roles')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.roles')</a></li>
                            <li class="active">@lang('admin.roles')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <table class="table table-bordered role-table">
                                <thead>
                                <tr>
                                  <th class="text-center">#</th>
                                  <th class="text-center">@lang('admin.role')</th>
                                  <th class="text-center"></th>
                                </tr>
                                </thead>
                              </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
 $(function () {
    var locale = '{{ config('app.locale') }}';
    if (locale == 'ar') {
    var table = $('.role-table').DataTable({
        "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"},
        processing: true,
        serverSide: true,
        ajax: "{{ route('roles.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name',searchable: true, sortable : true},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
        responsive:true,
        order:[0,'desc']
    }); 
        }else{
    var table = $('.role-table').DataTable({
        "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"},
        processing: true,
        serverSide: true,
        ajax: "{{ route('roles.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name',searchable: true, sortable : true},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
        responsive:true,
        order:[0,'desc']
    }); 
}  

    $('body').on('submit','#delform',function (e) {
        e.preventDefault();
        var url = $(this).attr('action');
        $.ajax({
          url: url,
          method: "delete",
          data: {
              _token: '{{ csrf_token() }}',
          },
          success: function (response) {

              if (response.status == 'success'){
                  new Noty({
                      type: 'success',
                      layout: 'topRight',
                      text: "@lang('admin.deletesuccessfully')",
                      timeout: 5000,
                      killer: true
                  }).show();
                  table.ajax.reload();
              }
              // console.log(response);
              
          }
        });
        })
});    
</script>

@endpush