routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\EntityController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ReserveController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TermController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::GET('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {

        Route::get('setting', [SettingController::class, 'index'])->name('setting');
        Route::post('setting', [SettingController::class, 'update'])->name('updatesetting');

        Route::resource('roles', RoleController::class)->except(['show']);

        Route::resource('terms', TermController::class)->except(['show']);
        
        Route::resource('admins', AdminsController::class)->except(['show']);
        Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

        Route::resource('users', UsersController::class)->except(['show']);
        Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');

        Route::resource('contactus', ContactController::class)->except(['create','edit']);
        Route::resource('aboutus', AboutController::class)->except(['show']);

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::get('categoryactive', [CategoryController::class, 'CategoryStatus'])->name('categoryactive');

        Route::resource('regions', RegionController::class)->except(['show']);
        Route::get('regionactive', [RegionController::class, 'RegionStatus'])->name('regionactive');

        Route::resource('entities', EntityController::class);
        Route::put('entityupdate2/{id}', [EntityController::class, 'updateStep2'])->name('updatestep2');
        Route::get('entityactive', [EntityController::class, 'EntityStatus'])->name('entityactive');
        Route::post('entityimagestore',[EntityController::class, 'EntityImage'])->name('entityimg');
        Route::get('entityimageshow',[EntityController::class, 'ShowImage'])->name('entityimgshow');
        Route::post('entityimagedelete',[EntityController::class, 'EntityImageDelete'])->name('entityimgdelete');

        Route::post('entityfeatadd',[EntityController::class, 'EntityFeatureAdd'])->name('entityfeatadd');
        Route::get('entityfeatall',[EntityController::class, 'EntityFeatureAll'])->name('entityfeatall');
        Route::delete('entityfeatdelete/{id}',[EntityController::class, 'EntityFeatureDelete'])->name('featureDelete');

        Route::post('entityfiltadd',[EntityController::class, 'EntityFilterAdd'])->name('entityfiltadd');
        Route::delete('entityfiltdelete/{id}',[EntityController::class, 'EntityFilterDelete'])->name('filterDelete');
        Route::delete('entityfiltoptiondelete/{id}',[EntityController::class, 'EntityOptionDelete'])->name('optionDelete');
        Route::post('entityoptiadd',[EntityController::class, 'EntityOptionAdd'])->name('entityoptionadd');

        Route::resource('reserves', ReserveController::class);
        Route::get('allres',[ReserveController::class, 'GetAllReseve'])->name('allreserve');
        
        });

        
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('/', function () {
            return view('welcome');
        });
        
        Auth::routes();
        
        Route::get('/home', [HomeController::class, 'index'])->name('home');
    });

app/Models/Terms.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;

class Terms extends Model
{
    use HasFactory;
    use Translatable;

    protected $table = 'terms';
    public $translatedAttributes = ['title', 'description'];

}

app/Http/Controllers/Admin/TermController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Terms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Str;

class TermController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:terms-read')->only(['index']);
        $this->middleware('permission:terms-create')->only(['create', 'store']);
        $this->middleware('permission:terms-update')->only(['edit', 'update']);
        $this->middleware('permission:terms-delete')->only(['destroy']);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Terms::all();
            return DataTables::of($data)
            ->addIndexColumn()
            ->editColumn('description', function ($query) {
                return Str::limit($query->description, 100);
            })
            ->addColumn('action', function($row){
            if (Auth::guard('admin')->user()->hasPermission('terms-update')){
             $btn ='<a href="' .route("terms.edit", $row->id). '" type="button" data-admid="'.$row->id.'" 
             class="btn btn-primary btn-xs edit"><i class="fa fa-pencil">
             </i></i></a> &nbsp;';
            }else{
                $btn = '<a  href="" class="btn btn-primary btn-xs disabled"><i class="fa fa-pencil"></i></i></a>';
            }
            if (Auth::guard('admin')->user()->hasPermission('terms-delete')){
                $btn = $btn.
                 '<form class=" delete"  action="' . route("terms.destroy", $row->id) . '"  method="POST" id="delform"
                style="display: inline-block; right: 50px;" >
                <input name="_method" type="hidden" value="DELETE">
                <input type="hidden" name="_token" value="' . csrf_token() . '">
                <button type="submit" class="btn btn-danger btn-xs" title=" ' . 'Delete' . ' "><i class="fa fa-trash-o"></i></button>
                </form>';
            }else{
                $btn = $btn. '<button class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></button>';
            }
                return $btn;
            })
                ->rawColumns(['action'])
                ->make(true);
            }

            return view('admin.terms.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.terms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    $request->validate([
        'ar.title' => 'required',
        'ar.description' => 'required',

        'en.title' => 'required',
        'en.description' => 'required',
    ]);

    $term = Terms::create([
        'ar' => [
            'title'       => $request->input('ar.title'),
            'description' => $request->input('ar.description')
        ],
        'en' => [
            'title'       => $request->input('en.title'),
            'description' => $request->input('en.description')
        ]
    ]);

      $term->save();

    return response()->json(['status'=>'success','data'=>$term]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $term = Terms::findOrFail($id);
        return view('admin.terms.edit',compact('term'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $term = Terms::findOrFail($id);
        $request->validate([
        'ar.title' => 'required',
        'ar.description' => 'required',
        
        'en.title' => 'required',
        'en.description' => 'required',
             ]);
        $term->update([
            'ar' => [
                'title'       => $request->input('ar.title'),
                'description' => $request->input('ar.description')
            ],
            'en' => [
                'title'       => $request->input('en.title'),
                'description' => $request->input('en.description')
            ]
        ]);
        $term->save();
        return response()->json(['status'=>'success','data'=>$term]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $term = Terms::findOrFail($id);
        $term->delete();
        return response()->json(['status'=>'success']);
    }
}

resources/views/admin/terms/create.blade.php
@extends('admin.layout.master')

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.terms')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.terms')</a></li>
                            <li class="active">@lang('admin.addterms')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">

                <form id="terms" method="post" data-parsley-validate>
                @csrf
                @method('post')
                
            @foreach (config('translatable.locales') as $locale)
                <div class="form-group col-md-6">
                    <label for="title">@lang('admin.' .$locale. '.termtitle')</label>
                    <input type="text" name="{{$locale}}[title]"
                        value="{{old($locale . '.title')}}" 
                        required parsley-trigger="change" 
                        placeholder="@lang('admin.'.$locale .'.termtitle')" 
                        class="form-control" >
                </div>
            @endforeach
                

                @foreach (config('translatable.locales') as $locale)
                <div class="form-group col-md-6">
                    <label for="description">@lang('admin.' .$locale. '.description')</label>
                    <textarea type="text" name="{{$locale}}[description]"
                        value="{{old($locale . '.description')}}" 
                        required parsley-trigger="change" 
                        placeholder="@lang('admin.'.$locale .'.description')" 
                        class="form-control" ></textarea>
                </div>
                @endforeach
               
                <div class="clearfix"></div>

                <div class="form-group text-right m-b-0">
                    @if(Auth::guard('admin')->user()->hasPermission('terms-create'))
                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.add')</button>
                    @else
                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.add')</button>
                    @endif
                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                </div>

                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
    $(function () {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#terms',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                $.ajax({
                    url: '{{ route('terms.store')}}',
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.addsuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/terms/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.terms')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.terms')</a></li>
                            <li class="active">@lang('admin.editterms')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <form id="terms" method="post" data-parsley-validate>
                                @csrf
                                @method('put')
                                <input type="hidden" name="termsId" id="terms_id" value="{{$term->id}}"  class="form-control">
                              
                                @foreach (config('translatable.locales') as $locale)
                                <div class="form-group col-md-6">
                                    <label for="title">@lang('admin.' .$locale. '.title')</label>
                                    <input type="text" name="{{$locale}}[title]"
                                        value="{{$term->translate($locale)->title}}" 
                                        required parsley-trigger="change" 
                                        placeholder="@lang('admin.'.$locale .'.title')" 
                                        class="form-control" >
                                </div>
                            @endforeach
                                
                
                                @foreach (config('translatable.locales') as $locale)
                                <div class="form-group col-md-6">
                                    <label for="description">@lang('admin.' .$locale. '.description')</label>
                                    <textarea type="text" name="{{$locale}}[description]"
                                        value="" 
                                        required parsley-trigger="change" 
                                        placeholder="@lang('admin.'.$locale .'.description')" 
                                        class="form-control" >{{$term->translate($locale)->description}}</textarea>
                                </div>
                                @endforeach


                
                                <div class="clearfix"></div>
                                <div class="form-group text-right m-b-0">
                                    @if(Auth::guard('admin')->user()->hasPermission('terms-update'))
                                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.edit')</button>
                                    @else
                                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.edit')</button>
                                    @endif
                                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                                </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#terms',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                 let id = $('#terms_id').val();
                 var url = '{{ route('terms.update', ':id') }}';
                  url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,
                    success: function (response) {
                        if (response.errors){
                            $.each(response.errors, function( index, value ) {
                                new Noty({
                                    type: 'success',
                                    layout: 'topRight',
                                    text: value,
                                    timeout: 2000,
                                    killer: true
                                }).show();
                            });
                        }
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.updatesuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/terms/index.blade.php
@extends('admin.layout.master')

@section('content')


<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm-12">
                            <h4 class="page-title">@lang('admin.terms')</h4>
                            <ol class="breadcrumb">
                                <li><a href="">@lang('admin.terms')</a></li>
                                <li class="active">@lang('admin.terms')</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <table class="table table-bordered role-table">
                                <thead>
                                <tr>
                                  <th class="text-center">#</th>
                                  <th class="text-center">@lang('admin.termtitle')</th>
                                  <th class="text-center">@lang('admin.description')</th>
                                  <th class="text-center"></th>
                                </tr>
                                </thead>
                              </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
 $(function () {
    var locale = '{{ config('app.locale') }}';
    //console.log(locale);
    if (locale == 'ar') {
        var table = $('.role-table').DataTable({
       "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"},
       processing: true,
       serverSide: true,
       ajax: "{{ route('terms.index') }}",
       
       columns: [
           {data: 'id', name: 'id'},
           {data: 'title', name: 'title',searchable: true, sortable : true},
           {data: 'description', name: 'description', sortable : true},
           {data: 'action', name: 'action', orderable: false, searchable: false},
       ],

       responsive:true,
       order:[0,'desc']
   });      
        } else {
    var table = $('.role-table').DataTable({
       
       "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"},
       processing: true,
       serverSide: true,
       ajax: "{{ route('terms.index') }}",
       
       columns: [
           {data: 'id', name: 'id'},
           {data: 'title', name: 'title',searchable: true, sortable : true},
           {data: 'description', name: 'description', sortable : true},
           {data: 'action', name: 'action', orderable: false, searchable: false},
       ],

       responsive:true,
       order:[0,'desc']
   }); 

}

    $('body').on('submit','#delform',function (e) {
        e.preventDefault();
        var url = $(this).attr('action');
        $.ajax({
          url: url,
          method: "delete",
          data: {
              _token: '{{ csrf_token() }}',
          },
          success: function (response) {

              if (response.status == 'success'){
                  new Noty({
                      type: 'success',
                      layout: 'topRight',
                      text: "@lang('admin.deletesuccessfully')",
                      timeout: 5000,
                      killer: true
                  }).show();
                  table.ajax.reload();
              } 
          }
        });
     })
});    
</script>

@endpush