routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\EntityController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ReserveController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TermController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::GET('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {

        Route::get('setting', [SettingController::class, 'index'])->name('setting');
        Route::post('setting', [SettingController::class, 'update'])->name('updatesetting');

        Route::resource('roles', RoleController::class)->except(['show']);

        Route::resource('terms', TermController::class)->except(['show']);
        
        Route::resource('admins', AdminsController::class)->except(['show']);
        Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

        Route::resource('users', UsersController::class)->except(['show']);
        Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');

        Route::resource('contactus', ContactController::class)->except(['create','edit']);
        Route::resource('aboutus', AboutController::class)->except(['show']);

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::get('categoryactive', [CategoryController::class, 'CategoryStatus'])->name('categoryactive');

        Route::resource('regions', RegionController::class)->except(['show']);
        Route::get('regionactive', [RegionController::class, 'RegionStatus'])->name('regionactive');

        Route::resource('entities', EntityController::class);
        Route::put('entityupdate2/{id}', [EntityController::class, 'updateStep2'])->name('updatestep2');
        Route::get('entityactive', [EntityController::class, 'EntityStatus'])->name('entityactive');
        Route::post('entityimagestore',[EntityController::class, 'EntityImage'])->name('entityimg');
        Route::get('entityimageshow',[EntityController::class, 'ShowImage'])->name('entityimgshow');
        Route::post('entityimagedelete',[EntityController::class, 'EntityImageDelete'])->name('entityimgdelete');

        Route::post('entityfeatadd',[EntityController::class, 'EntityFeatureAdd'])->name('entityfeatadd');
        Route::get('entityfeatall',[EntityController::class, 'EntityFeatureAll'])->name('entityfeatall');
        Route::delete('entityfeatdelete/{id}',[EntityController::class, 'EntityFeatureDelete'])->name('featureDelete');

        Route::post('entityfiltadd',[EntityController::class, 'EntityFilterAdd'])->name('entityfiltadd');
        Route::delete('entityfiltdelete/{id}',[EntityController::class, 'EntityFilterDelete'])->name('filterDelete');
        Route::delete('entityfiltoptiondelete/{id}',[EntityController::class, 'EntityOptionDelete'])->name('optionDelete');
        Route::post('entityoptiadd',[EntityController::class, 'EntityOptionAdd'])->name('entityoptionadd');

        Route::resource('reserves', ReserveController::class);
        Route::get('allres',[ReserveController::class, 'GetAllReseve'])->name('allreserve');
        
        });

        
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('/', function () {
            return view('welcome');
        });
        
        Auth::routes();
        
        Route::get('/home', [HomeController::class, 'index'])->name('home');
    });

resources/views/admin/admins/create.blade.php
@extends('admin.layout.master')

@push('css')
<style>
.field-icon {
  float: left;
  margin-left: 15px;
  margin-top: -25px;
  position: relative;
  z-index: 2;
}
</style>
@endpush
@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.admins')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.admins')</a></li>
                            <li class="active">@lang('admin.addadmins')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                <form id="admins" method="post" data-parsley-validate>
                @csrf
                @method('post')

                <div class="form-group col-md-6">
                    <label for="name">@lang('admin.name')</label>
                    <input type="text" name="name"
                        value="{{old('name')}}" 
                        required parsley-trigger="change" 
                        placeholder="@lang('admin.name')" 
                        class="form-control" >
                </div>

                <div class="form-group col-md-6">
                    <label for="email">@lang('admin.email')</label>
                    <input type="email" name="email"
                        value="{{old('email')}}" 
                        required parsley-trigger="change" 
                        placeholder="@lang('admin.email')" 
                        class="form-control" >
                </div>

                <div class="form-group col-md-6" >
                    <label for="password">@lang('admin.password')</label>
                    <input type="password" name="password"
                        value="{{old('password')}}" 
                        required parsley-trigger="change" 
                        placeholder="@lang('admin.password')" 
                        class="form-control" id="password-field">
                        <span toggle="#password-field" class="fa fa-fw fa-eye-slash field-icon toggle-password"></span>
                </div>
                
                <div class="form-group col-md-6">
                    <label for="role_id"> @lang('admin.roles')</label>
                    <select class="form-control select2" name="role_id" required parsley-trigger="change" >
                        @foreach($roles as $role)
                            <option value="{{$role->id}}">{{$role->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="clearfix"></div>
                <div class="form-group text-right m-b-0">
                    @if(Auth::guard('admin')->user()->hasPermission('admins-create'))
                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.add')</button>
                    @else
                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.add')</button>
                    @endif
                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                </div>
                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')

<script>
    $(".toggle-password").click(function() {
    $(this).toggleClass("fa-eye fa-eye-slash");
        var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
            input.attr("type", "text");
            } else {
            input.attr("type", "password");
            }
    });
</script>
<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#admins',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                $.ajax({
                    url: '{{ route('admins.store')}}',
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.addsuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/admins/edit.blade.php
@extends('admin.layout.master')

@push('css')
<style>
.field-icon {
  float: left;
  margin-left: 15px;
  margin-top: -25px;
  position: relative;
  z-index: 2;
}
</style>
@endpush

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.admins')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.admins')</a></li>
                            <li class="active">@lang('admin.editadmins')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <form id="admins" method="post" data-parsley-validate>
                                @csrf
                                @method('put')
                                <input type="hidden" name="AdminId" id="admin_id" value="{{$admin->id}}"  class="form-control">
                                <div class="form-group col-md-6">
                                    <label for="name">@lang('admin.name')</label>
                                    <input type="text" name="name"
                                        value="{{$admin->name}}" 
                                        required parsley-trigger="change" 
                                        placeholder="@lang('admin.name')" 
                                        class="form-control" >
                                </div>
                
                                <div class="form-group col-md-6">
                                    <label for="email">@lang('admin.email')</label>
                                    <input type="email" name="email"
                                        value="{{$admin->email}}" 
                                        required parsley-trigger="change" 
                                        placeholder="@lang('admin.email')" 
                                        class="form-control" >
                                </div>
                
                                <div class="form-group col-md-6">
                                    <label for="password">@lang('admin.password')</label>
                                    <input type="password" name="password"
                                        value="{{old('password')}}" 
                                        placeholder="@lang('admin.password')" 
                                        class="form-control" id="password-field">
                                        <span toggle="#password-field" class="fa fa-fw fa-eye-slash field-icon toggle-password"></span>
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <label for="role_id"> @lang('admin.roles')</label>
                                    <select class="form-control select2" name="role_id">
                                        <option>@lang('admin.roles')</option>
                                        @foreach($roles as $role)
                                            <option  value="{{$role->id}}" {{$admin->hasRole($role->name) == 'true'? 'selected':''}}>{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                
                                <div class="clearfix"></div>
                                <div class="form-group text-right m-b-0">
                                    @if(Auth::guard('admin')->user()->hasPermission('admins-update'))
                                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.edit')</button>
                                    @else
                                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.edit')</button>
                                    @endif
                                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                                </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')

 <script>
$(".toggle-password").click(function() {
    $(this).toggleClass("fa-eye fa-eye-slash");
        var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
            input.attr("type", "text");
            } else {
            input.attr("type", "password");
            }
    });
 </script>

<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#admins',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                 let id = $('#admin_id').val();
                 var url = '{{ route('admins.update', ':id') }}';
                  url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if (response.errors){
                            $.each(response.errors, function( index, value ) {

                                // console.log(value);

                                new Noty({
                                    type: 'success',
                                    layout: 'topRight',
                                    text: value,
                                    timeout: 2000,
                                    killer: true
                                }).show();
                            });
                        }
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.updatesuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/admins/index.blade.php
@extends('admin.layout.master')

@section('content')


<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm-12">
                            <h4 class="page-title">@lang('admin.admins')</h4>
                            <ol class="breadcrumb">
                                <li><a href="">@lang('admin.admins')</a></li>
                                <li class="active">@lang('admin.admins')</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <table class="table table-bordered role-table">
                                <thead>
                                <tr>
                                  <th class="text-center">#</th>
                                  <th class="text-center">@lang('admin.name')</th>
                                  <th class="text-center">@lang('admin.email')</th>
                                  <th class="text-center">@lang('admin.role')</th>
                                  <th class="text-center">@lang('admin.active')</th>
                                  <th class="text-center"></th>
                                </tr>
                                </thead>
                              </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
 $(function () {
    var locale = '{{ config('app.locale') }}';
    //console.log(locale);
    if (locale == 'ar') {
        var table = $('.role-table').DataTable({
       "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"},
       processing: true,
       serverSide: true,
       ajax: "{{ route('admins.index') }}",
       
       columns: [
           {data: 'id', name: 'id'},
           {data: 'name', name: 'name',searchable: true, sortable : true},
           {data: 'email', name: 'email',searchable: true, sortable : true},
           {data: 'role_id', name: 'role_id'},
           {data: 'active', name: 'active', orderable: false, searchable: false},
           {data: 'action', name: 'action', orderable: false, searchable: false},
       ],

       responsive:true,
       order:[0,'desc']
   });      
        } else {
            var table = $('.role-table').DataTable({
       
       "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"},
       processing: true,
       serverSide: true,
       ajax: "{{ route('admins.index') }}",
       
       columns: [
           {data: 'id', name: 'id'},
           {data: 'name', name: 'name',searchable: true, sortable : true},
           {data: 'email', name: 'email',searchable: true, sortable : true},
           {data: 'role_id', name: 'role_id'},
           {data: 'active', name: 'active', orderable: false, searchable: false},
           {data: 'action', name: 'action', orderable: false, searchable: false},
       ],

       responsive:true,
       order:[0,'desc']
   }); 

}
        
$('body').on('click','#check',function () {
    //e.preventDefault();
    var active = $(this).prop('checked') == true ? 1 : 0; 
    var admin_id = $(this).data('id');
     $.ajax({
        url:'{{ route('adminactive') }}',
        type:'GET',
        data:{
            'active':active,
            'admin_id': admin_id
        },
         success: function (response) {
         if (response.status == 'success'){
             new Noty({
                type: 'success',
                layout: 'topRight',
                text: "@lang('admin.statuschange')",
                timeout: 5000,
                killer: true
              }).show();
            }
        }
    });
});

    $('body').on('submit','#delform',function (e) {
        e.preventDefault();
        var url = $(this).attr('action');
        $.ajax({
          url: url,
          method: "delete",
          data: {
              _token: '{{ csrf_token() }}',
          },
          success: function (response) {

              if (response.status == 'success'){
                  new Noty({
                      type: 'success',
                      layout: 'topRight',
                      text: "@lang('admin.deletesuccessfully')",
                      timeout: 5000,
                      killer: true
                  }).show();
                  table.ajax.reload();
              }  
           }
        });
    })
});    
</script>



@endpush