routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\EntityController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ReserveController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TermController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::GET('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {

        Route::get('setting', [SettingController::class, 'index'])->name('setting');
        Route::post('setting', [SettingController::class, 'update'])->name('updatesetting');

        Route::resource('roles', RoleController::class)->except(['show']);

        Route::resource('terms', TermController::class)->except(['show']);
        
        Route::resource('admins', AdminsController::class)->except(['show']);
        Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

        Route::resource('users', UsersController::class)->except(['show']);
        Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');

        Route::resource('contactus', ContactController::class)->except(['create','edit']);
        Route::resource('aboutus', AboutController::class)->except(['show']);

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::get('categoryactive', [CategoryController::class, 'CategoryStatus'])->name('categoryactive');

        Route::resource('regions', RegionController::class)->except(['show']);
        Route::get('regionactive', [RegionController::class, 'RegionStatus'])->name('regionactive');

        Route::resource('entities', EntityController::class);
        Route::put('entityupdate2/{id}', [EntityController::class, 'updateStep2'])->name('updatestep2');
        Route::get('entityactive', [EntityController::class, 'EntityStatus'])->name('entityactive');
        Route::post('entityimagestore',[EntityController::class, 'EntityImage'])->name('entityimg');
        Route::get('entityimageshow',[EntityController::class, 'ShowImage'])->name('entityimgshow');
        Route::post('entityimagedelete',[EntityController::class, 'EntityImageDelete'])->name('entityimgdelete');

        Route::post('entityfeatadd',[EntityController::class, 'EntityFeatureAdd'])->name('entityfeatadd');
        Route::get('entityfeatall',[EntityController::class, 'EntityFeatureAll'])->name('entityfeatall');
        Route::delete('entityfeatdelete/{id}',[EntityController::class, 'EntityFeatureDelete'])->name('featureDelete');

        Route::post('entityfiltadd',[EntityController::class, 'EntityFilterAdd'])->name('entityfiltadd');
        Route::delete('entityfiltdelete/{id}',[EntityController::class, 'EntityFilterDelete'])->name('filterDelete');
        Route::delete('entityfiltoptiondelete/{id}',[EntityController::class, 'EntityOptionDelete'])->name('optionDelete');
        Route::post('entityoptiadd',[EntityController::class, 'EntityOptionAdd'])->name('entityoptionadd');

        Route::resource('reserves', ReserveController::class);
        Route::get('allres',[ReserveController::class, 'GetAllReseve'])->name('allreserve');
        
        });

        
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\AdminController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        
        Route::get('/', function () {
            return view('welcome');
        });
        
        Auth::routes();
        
        Route::get('/home', [HomeController::class, 'index'])->name('home');
    });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;

class Category extends Model
{
    use HasFactory;
    use Translatable;

    protected $table = 'categories';

    public $translatedAttributes = ['title'];

    protected $fillable = [
        'image',
        'active',
    ];

    protected $appends = ['image_path'];
   
    public function getImagePathAttribute()
    {
        return asset('uploads/categories/' . $this->image);
    }
    
    public function entities()
    {
        return $this->hasMany(Entity::class);
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\ImageManagerStatic as Image;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:regions-read')->only(['index']);
        $this->middleware('permission:regions-create')->only(['create', 'store']);
        $this->middleware('permission:regions-update')->only(['edit', 'update']);
        $this->middleware('permission:regions-delete')->only(['destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Category::all();
            return DataTables::of($data)
            ->addIndexColumn()
            ->editColumn('active', function ($query) {
                if ($query->active) {
                    $btn = '
            <div align="center">
            <label class="switch">
            <input data-id="' . $query->id . '" type="checkbox" id="check" checked>
                <div class="slider round">
                    <span class="on">ON</span>
                    <span class="off">OFF</span>
                </div>
            </label>
          </div>';
                } else {
                    $btn = '
                <div align="center">
                <label class="switch">
                <input data-id="' . $query->id . '" type="checkbox" id="check">
                    <div class="slider round">
                        <span class="on">ON</span>
                        <span class="off">OFF</span>
                    </div>
                </label>
              </div>';
                }

                return $btn;
            })
            ->addColumn('image', function ($query) {
            return '<img src=' . $query->image_path . ' border="0" style=" width: 250px; height: 130px;" class="image-show" />';
               })
            ->addColumn('action', function($row){
            if (Auth::guard('admin')->user()->hasPermission('categories-update')){
             $btn ='<a href="' .route("categories.edit", $row->id). '" type="button" data-admid="'.$row->id.'" 
             class="btn btn-primary btn-xs edit"><i class="fa fa-pencil">
             </i></i></a> &nbsp;';
            }else{
                $btn = '<a  href="" class="btn btn-primary btn-xs disabled"><i class="fa fa-pencil"></i></i></a>';
            }
            if (Auth::guard('admin')->user()->hasPermission('categories-delete')){
                $btn = $btn.
                 '<form class=" delete"  action="' . route("categories.destroy", $row->id) . '"  method="POST" id="delform"
                style="display: inline-block; right: 50px;" >
                <input name="_method" type="hidden" value="DELETE">
                <input type="hidden" name="_token" value="' . csrf_token() . '">
                <button type="submit" class="btn btn-danger btn-xs" title=" ' . 'Delete' . ' "><i class="fa fa-trash-o"></i></button>
                </form>';
            }else{
                $btn = $btn. '<button class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></button>';
            }
                return $btn;
            })
                ->rawColumns(['action','image','active'])
                ->make(true);
            }

            return view('admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {    
       $request->validate([
        'ar.title' => 'required',
        'en.title' => 'required',
           ]);
  
            $category = Category::create([
                'ar' => [
                    'title'       => $request->input('ar.title'),
                ],
                'en' => [
                    'title'       => $request->input('en.title'),
                ]
            ]);

            if ($request->image) {
                Image::make($request->image)->resize(300, null, function ($constraint) {
                    $constraint->aspectRatio();
                })->save(public_path('uploads/categories/' . $request->image->hashName()));
            }
            $category->image = $request->image->hashName();

    $category->save();

    return response()->json(['status'=>'success','data'=>$category]);
    }


    public function CategoryStatus(Request $request)
    {
        $category = Category::find($request->category_id);
        $category->active = $request->active;
        $category->save();

        return response()->json(['status' => 'success', 'data' => $category]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $request->validate([
                'ar.title' => 'required',
                'en.title' => 'required',
             ]);
        $category->update([
            'ar' => [
                'title'       => $request->input('ar.title'),
            ],
            'en' => [
                'title'       => $request->input('en.title'),
            ]
        ]);

        if ($request->image) {
            Image::make($request->image)->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/categories/' . $request->image->hashName()));
            $category->image = $request->image->hashName();
        }

        $category->save();
        return response()->json(['status'=>'success','data'=>$category]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        Storage::disk('public_uploads')->delete('/categories/' . $category->image);
        $category->delete();
        return response()->json(['status'=>'success']);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout.master')

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.categories')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.categories')</a></li>
                            <li class="active">@lang('admin.addcategory')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">

                <form id="categories" method="post" enctype="multipart/form-data" data-parsley-validate>
                @csrf
                @method('post')
                
            @foreach (config('translatable.locales') as $locale)
                <div class="form-group col-md-6">
                    <label for="title">@lang('admin.' .$locale. '.title')</label>
                    <input type="text" name="{{$locale}}[title]"
                        value="{{old($locale . '.title')}}" 
                        required parsley-trigger="change" 
                        placeholder="@lang('admin.'.$locale .'.title')" 
                        class="form-control" >
                </div>
            @endforeach
            
                <div class="form-group col-md-6" style="text-align: center;margin-top: 17px;">
                    <label for="image"> @lang('admin.image')</label>
                    <input type="file" name="image" id="image" class="filestyle image" data-buttonname="btn-primary" required>
                </div>

                <div class="form-group col-md-6">
                    <img src="" 
                    width="250" height="130" alt="" 
                    style="margin-right: 50px;" 
                    class="image-show"/>
                 </div>
               
                <div class="clearfix"></div>

                <div class="form-group text-right m-b-0">
                    @if(Auth::guard('admin')->user()->hasPermission('aboutus-create'))
                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.add')</button>
                    @else
                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.add')</button>
                    @endif
                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                </div>

                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
    $(function () {

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

            $('body').on('submit','#categories',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                $.ajax({
                    url: '{{ route('categories.store')}}',
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.addsuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/categories/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">@lang('admin.categories')</h4>
                        <ol class="breadcrumb">
                            <li><a href="">@lang('admin.categories')</a></li>
                            <li class="active">@lang('admin.editcategories')</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <form id="categories" method="post" enctype="multipart/form-data" data-parsley-validate>
                                @csrf
                                @method('put')
                                <input type="hidden" name="categoryId" id="category_id" value="{{$category->id}}"  class="form-control">
                              
                                @foreach (config('translatable.locales') as $locale)
                                <div class="form-group col-md-6">
                                    <label for="title">@lang('admin.' .$locale. '.title')</label>
                                    <input type="text" name="{{$locale}}[title]"
                                        value="{{$category->translate($locale)->title}}" 
                                        required parsley-trigger="change" 
                                        placeholder="@lang('admin.'.$locale .'.title')" 
                                        class="form-control" >
                                </div>
                            @endforeach
                
                                <div class="form-group col-md-6" style="text-align: center;margin-top: 17px;">
                                    <label for="image"> @lang('admin.image')</label>
                                    <input type="file" name="image" id="image" class="filestyle image" data-buttonname="btn-primary">
                                </div>
                
                                <div class="form-group col-md-6">
                                    <img src="{{$category->image_path}}" 
                                    width="250" height="130" alt="" 
                                    style="margin-right: 50px;" 
                                    class="image-show"/>
                                 </div>
                               
                

                
                                <div class="clearfix"></div>
                                <div class="form-group text-right m-b-0">
                                    @if(Auth::guard('admin')->user()->hasPermission('categories-update'))
                                    <button class="btn btn-primary waves-effect waves-light" type="submit" name="submit">@lang('admin.edit')</button>
                                    @else
                                    <button class="btn btn-primary waves-effect waves-light" disabled>@lang('admin.edit')</button>
                                    @endif
                                    <button type="reset" class="btn btn-default waves-effect waves-light m-l-5">@lang('admin.cancel')</button>
                                </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#categories',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                 let id = $('#category_id').val();
                 var url = '{{ route('categories.update', ':id') }}';
                  url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if (response.errors){
                            $.each(response.errors, function( index, value ) {

                                // console.log(value);

                                new Noty({
                                    type: 'success',
                                    layout: 'topRight',
                                    text: value,
                                    timeout: 2000,
                                    killer: true
                                }).show();
                            });
                        }
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.updatesuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('admin.layout.master')

@section('content')


<div class="wrapper">
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm-12">
                            <h4 class="page-title">@lang('admin.aboutus')</h4>
                            <ol class="breadcrumb">
                                <li><a href="">@lang('admin.aboutus')</a></li>
                                <li class="active">@lang('admin.aboutus')</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-box">
                            <table class="table table-bordered role-table">
                                <thead>
                                <tr>
                                  <th class="text-center">#</th>
                                  <th class="text-center">@lang('admin.title')</th>
                                  <th class="text-center">@lang('admin.image')</th>
                                  <th class="text-center">@lang('admin.active')</th>
                                  <th class="text-center"></th>
                                </tr>
                                </thead>
                              </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
 $(function () {
    var locale = '{{ config('app.locale') }}';
    //console.log(locale);
    if (locale == 'ar') {
        var table = $('.role-table').DataTable({
       "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"},
       processing: true,
       serverSide: true,
       ajax: "{{ route('categories.index') }}",
       
       columns: [
           {data: 'id', name: 'id'},
           {data: 'title', name: 'title',searchable: true, sortable : true},
           {data: 'image', name: 'image', sortable : true},
           {data: 'active', name: 'active', orderable: false, searchable: false},
           {data: 'action', name: 'action', orderable: false, searchable: false},
       ],

       responsive:true,
       order:[0,'desc']
   });      
        } else {
            var table = $('.role-table').DataTable({
       
       "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"},
       processing: true,
       serverSide: true,
       ajax: "{{ route('categories.index') }}",
       
       columns: [
           {data: 'id', name: 'id'},
           {data: 'title', name: 'title',searchable: true, sortable : true},
           {data: 'image', name: 'image', sortable : true},
           {data: 'active', name: 'active', orderable: false, searchable: false},
           {data: 'action', name: 'action', orderable: false, searchable: false},
       ],

       responsive:true,
       order:[0,'desc']
   }); 

}
        
$('body').on('click','#check',function () {
    //e.preventDefault();
    var active = $(this).prop('checked') == true ? 1 : 0; 
    var category_id = $(this).data('id');
     $.ajax({
        url:'{{ route('categoryactive') }}',
        type:'GET',
        data:{
            'active':active,
            'category_id': category_id
        },
         success: function (response) {
         if (response.status == 'success'){
             new Noty({
                type: 'success',
                layout: 'topRight',
                text: "@lang('admin.statuschange')",
                timeout: 5000,
                killer: true
              }).show();
            }
        }
    });
});


    $('body').on('submit','#delform',function (e) {
        e.preventDefault();
        var url = $(this).attr('action');
        $.ajax({
          url: url,
          method: "delete",
          data: {
              _token: '{{ csrf_token() }}',
          },
          success: function (response) {

              if (response.status == 'success'){
                  new Noty({
                      type: 'success',
                      layout: 'topRight',
                      text: "@lang('admin.deletesuccessfully')",
                      timeout: 5000,
                      killer: true
                  }).show();
                  table.ajax.reload();
              }
          }
        });
        })
});    
</script>

@endpush